# Workflowの名前 (任意の名前でOK)
name: 'dependabot random assign'

# どのイベントが発生したときにWorkflowを実行するかを指定
# 今回はPull Requestイベントのときのみ実行
on: 
  pull_request:
    types: opened

jobs:
  assign-dependabot-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Set reviewer
        env:
          REVIEWERS: mana0123
        run: |
          reviewer_count=$(cat ${{ github.event_path }} | jq '.pull_request.requested_reviewers | length')
          if [[ 0 == $reviewer_count ]]; then
            curl -X POST \
                 -H "Content-Type: application/json" \
                 -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d "{ \"reviewers\": $REVIEWERS }" \
                 https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/requested_reviewers
          fi
